
server:
  port: 10010 # 网关服务端口
spring:
  application:
    name: api-gateway #网关服务名称

############### 编写路由规则 1.0 ##########################################################
# 网关作为统一的入口，现在再要访问user-service-demo的服务，就得按照网关的规则来
# 通过localhost:10010/user-service-demo/user/10 而不是之前的localhost:8081/user/10访问
# zuul:
#  routes:
#    user-service:                          # 这里是路由的id，随意填写
#      path: /user-service-demo/**          # 映射路径，将/user-service-demo/开头的请求代理到下面实际地址
#      url: http://127.0.0.1:8081           # 映射路径对应的实际url地址

############## 编写路由规则 2.0 ###########################################################
# 上面的配置有问题吗？路径对应地址写死了，若一个服务有多个实例，上述做法显然不合理

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10087/eureka  # 注册中心的地址
    registry-fetch-interval-seconds: 5         #  5秒获取一次服务地址列表
  instance:
    prefer-ip-address: true                     # 获取实例的hostname时，返回ip而不是host名称
    ip-address: 127.0.0.1                        # 指定自己的ip信息，若不指定会自动寻找

# 比较常规的写法
zuul:
  prefix: /api    添加路由前缀  加了前缀以后，之后发起请求都要有前缀开头 /api/user-service-demo/user
  routes:
    user-service:                               # 这里是路由的id，随意填写
      path: /user-service-demo/**
      serviceId: user-service-demo              # 区别于上面直接指定地址，这里指定服务名称
  retryable: true                              # 允许重试

# 简化的写法，通常情况，路由id与serviceId会写成一致
# 所以上面的常规写法 可以用zuul.routes.<serviceId>=<path>
#zuul:
#  routes:
#    user-service: /user-service-demo/**

# 默认路由配置，一切服务的映射路径就是服务名本身--------除非需要个性化，否则上述写法不配置也会生效

################ Zuul默认集成Ribbon和Hystrix ################################################################
# 超时策略都是默认值，很容易触发，需要手动修改
ribbon:
  ConnectTimeout: 250                    #  连接超时时间 ms
  ReadTimeout: 2000                      #  通信超时时间 ms ，数据读取时间，要小于Hystrix的超时时间
  OkToRetryOnAllOperations: true       #  是否对所有操作重试
  MaxAutoRetriesNextServer: 2          #  同一服务不同实例的重试次数
  MaxAutoRetries: 1                     #  同一实例的重试次数
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 6000  # 熔断时长6000毫秒

